<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E MEDIA WhatsApp API — Register</title>
    <style>
        body { font-family: system-ui, sans-serif; background: #f0f2f5; margin: 0; padding: 40px 16px; }
        .card { max-width: 480px; margin: 0 auto; background: #fff; border-radius: 12px; padding: 32px; box-shadow: 0 2px 12px rgba(0,0,0,.08); }
        h1 { margin: 0 0 4px; font-size: 22px; color: #128c7e; }
        p.sub { color: #667781; margin: 0 0 24px; font-size: 14px; }
        label { display: block; font-size: 13px; font-weight: 600; margin-bottom: 6px; color: #333; }
        input { width: 100%; padding: 10px 12px; border: 1px solid #ddd; border-radius: 8px; font-size: 14px; box-sizing: border-box; margin-bottom: 16px; }
        button { width: 100%; padding: 12px; background: #128c7e; color: #fff; border: none; border-radius: 8px; font-size: 15px; font-weight: 600; cursor: pointer; }
        .alert { padding: 12px 14px; border-radius: 8px; margin-bottom: 16px; font-size: 14px; }
        .alert-success { background: #d9f7e5; color: #075e54; }
        .key-box { background: #1e1e2e; color: #cdd6f4; padding: 12px; border-radius: 8px; font-size: 12px; word-break: break-all; margin-top: 8px; }
    </style>
</head>
<body>
    <div class="card">
        <h1>E MEDIA WhatsApp API</h1>
        <p class="sub">Register your email to get API access. Admin approval required before sending.</p>

        @if(session('status.success'))
            <div class="alert alert-success">
                {{ session('status.msg') }}
                @if(session('status.api_key'))
                    <div><strong>Email:</strong> {{ session('status.email') }}</div>
                    <div class="key-box">{{ session('status.api_key') }}</div>
                    <small>Save this key — it won't be shown again unless regenerated by admin.</small>
                @endif
            </div>
        @endif

        <form method="POST" action="{{ route('emwa.register') }}">
            @csrf
            <label for="name">Name / Company</label>
            <input type="text" id="name" name="name" value="{{ old('name') }}" required placeholder="Your business name">
            @error('name')<div style="color:#c0392b;font-size:12px;margin:-12px 0 12px;">{{ $message }}</div>@enderror

            <label for="email">Email</label>
            <input type="email" id="email" name="email" value="{{ old('email') }}" required placeholder="youremail@gmail.com">
            @error('email')<div style="color:#c0392b;font-size:12px;margin:-12px 0 12px;">{{ $message }}</div>@enderror

            <button type="submit">Register for API Access</button>
        </form>
    </div>
</body>
</html>
