#!/bin/bash
# Create a minimal .env file on Coolify when vars are injected but no .env exists.
# Skips the web installer redirect (IsInstalled middleware checks APP_KEY / .env).
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [ -f .env ]; then
    echo "==> .env already exists."
    exit 0
fi

if [ -z "$APP_KEY" ]; then
    echo "==> APP_KEY not set — add it in Coolify Environment Variables."
    exit 1
fi

cat > .env <<EOF
# Auto-generated by scripts/ensure-env-file.sh (Coolify deploy)
# Runtime values are injected by Coolify; this file marks the app as installed.
APP_NAME="${APP_NAME:-PrintWorks}"
APP_ENV="${APP_ENV:-production}"
APP_KEY="${APP_KEY}"
APP_DEBUG="${APP_DEBUG:-false}"
APP_URL="${APP_URL:-https://erp.printworks.lk}"

DB_CONNECTION="${DB_CONNECTION:-mysql}"
DB_HOST="${DB_HOST}"
DB_PORT="${DB_PORT:-3306}"
DB_DATABASE="${DB_DATABASE}"
DB_USERNAME="${DB_USERNAME}"
DB_PASSWORD="${DB_PASSWORD}"
EOF

chmod 644 .env 2>/dev/null || true
echo "==> Created .env stub for Coolify."
